"""How much of the sampling error is the choice of partition?

Production hardcodes partition 0. This runs every partition at each rate and
compares them, which separates bias (does the estimator sit off-centre?) from
variance (how much does the answer depend on which partition you got?).

    plot_partitions.py <curves_dir> <out.png>

<curves_dir> holds s<rate>_p<partition>.csv for rate 0..3, generated by samp_part.cc.
"""
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _common import BLOCK, common_grid, load_dir, miss_at

CURVES = sys.argv[1]
OUT = sys.argv[2] if len(sys.argv) > 2 else "sampling_partitions.png"
RATES = [1, 2, 3]

curves = {(s, p): load_dir(CURVES, s, p) for s in RATES for p in range(1 << s)}
curves[(0, 0)] = load_dir(CURVES, 0, 0)
grid = common_grid(list(curves.values()))
miss = {k: miss_at(*v, grid) for k, v in curves.items()}
mb = grid * BLOCK / (1024 * 1024)
exact = miss[(0, 0)]

colors = {1: "#1f77b4", 2: "#d62728", 3: "#2ca02c"}
fig, axes = plt.subplots(1, 3, figsize=(19, 5.4))

# Panel 1: every partition, so the spread is visible directly.
ax = axes[0]
ax.plot(mb, exact, color="#111111", lw=2.4, label="exact")
for s in RATES:
    for p in range(1 << s):
        ax.plot(mb, miss[(s, p)], color=colors[s], lw=0.9, alpha=0.5,
                label="1-in-%d (all %d partitions)" % (1 << s, 1 << s) if p == 0 else None)
ax.set_xscale("log")
ax.set_xlabel("cache size (MiB, log)")
ax.set_ylabel("miss ratio")
ax.set_title("Every partition, every rate")
ax.grid(alpha=.3)
ax.legend(fontsize=9)

# Panel 2: spread band vs the mean of partitions. If the mean tracks zero, the
# estimator is unbiased and the problem is purely which partition you drew.
ax = axes[1]
for s in RATES:
    band = np.array([miss[(s, p)] for p in range(1 << s)])
    ax.fill_between(mb, (band.min(0) - exact) * 100, (band.max(0) - exact) * 100,
                    color=colors[s], alpha=0.18)
    ax.plot(mb, (band.mean(0) - exact) * 100, color=colors[s], lw=1.9,
            label="1-in-%d: mean of partitions" % (1 << s))
ax.axhline(0, color="#111111", lw=1)
ax.set_xscale("log")
ax.set_xlabel("cache size (MiB, log)")
ax.set_ylabel("miss-ratio error (percentage points)")
ax.set_title("Partition spread (band) vs mean of partitions (line)")
ax.grid(alpha=.3)
ax.legend(fontsize=9)

# Panel 3: partition 0 on its own -- what production actually reports.
ax = axes[2]
for s in RATES:
    ax.plot(mb, (miss[(s, 0)] - exact) * 100, color=colors[s], lw=1.8,
            label="1-in-%d, partition 0" % (1 << s))
ax.axhline(0, color="#111111", lw=1)
ax.set_xscale("log")
ax.set_xlabel("cache size (MiB, log)")
ax.set_ylabel("miss-ratio error (pp)")
ax.set_title("Partition 0 alone -- the one production ships")
ax.grid(alpha=.3)
ax.legend(fontsize=9)

plt.tight_layout()
plt.savefig(OUT, dpi=130)

print("%-8s %10s %10s %10s %10s" % ("rate", "p0 max", "mean max", "spread", "bias"))
for s in RATES:
    band = np.array([miss[(s, p)] for p in range(1 << s)])
    e0 = np.abs(miss[(s, 0)] - exact) * 100
    em = np.abs(band.mean(0) - exact) * 100
    spread = ((band.max(0) - band.min(0)) * 100).max()
    print("1-in-%-3d %9.3fpp %9.3fpp %9.3fpp %9.3fpp"
          % ((1 << s), e0.max(), em.max(), spread, ((band.mean(0) - exact) * 100).mean()))
print("wrote %s" % OUT)
